ideas_task:
  description: >
    You are a Real Estate Marketing Trend Analyst specializing in {Location}. Your task is to generate insightful
    blog post ideas that capture current and emerging real estate trends in this area. Consider the following
    factors in your analysis but dont strictly adhear to them, use similar phrases and think outside of the box:
    Economic Indicators
    Current interest rates and mortgage availability
    Local and national economic growth patterns in {Location}
    Inflation rates and their impact on real estate
    Employment rates and job market trends in {Location}
    Market Dynamics
    Supply and demand balance in {Location}
    Current phase of the real estate market cycle (boom, bust, or recovery)
    Inventory levels and time on market for properties in {Location}
    Regulatory Environment
    Recent changes in zoning laws and land use regulations in {Location}
    Tax policies and incentives affecting real estate in {Location}
    Building codes and their impact on development in {Location}
    Demographic Trends
    Population growth and migration patterns in {Location}
    Age distribution and its effect on housing demand in {Location}
    Changes in household size and composition in {Location}
    Development and Infrastructure
    Upcoming infrastructure projects in {Location}
    Urban development plans and their potential impact in {Location}
    Gentrification or revitalization efforts in specific neighborhoods in {Location}
    Environmental Factors
    Climate change considerations for {Location}
    Natural disaster risks and their influence on real estate in {Location}
    Proximity to bodies of water or scenic views in {Location}
    Property Characteristics
    Popular features and amenities in demand in {Location}
    Emerging architectural or design trends in {Location}
    Energy efficiency and smart home technology adoption in {Location}
    Investment Trends
    Rise of real estate investment trusts (REITs) or crowdfunding platforms
    Foreign investment patterns in {Location}
    Shifts between residential and commercial real estate investments in {Location}
    Based on these factors, generate blog post ideas that provide valuable insights for potential buyers,
    sellers, investors, and real estate professionals in {Location}. Your content should be data-driven,
    forward-looking, and tailored to the unique characteristics of the local market.
  expected_output: >
    A list of ideas for 10 full blog posts relevant to in individual neighborhoods in {Location} in {year}.

research_task:
  description: >
    Conduct thorough research on the given topic from the ideas_task in {Location} {year}. Ensure you find any interesting and relevant information.  Use ALL of the tools avaliable to you Dont just use one.
    The current year is {year}. rephrase your search queries each time you use the search tool and make sure they are unique. Choose a different search query each time! We want a diverse set of information. 
    DONT REPEAT YOUSELF when using the search tools! Use all of your tools not just one!
    Chose a random rsult each time, not just the first one.
  expected_output: >
    Research for the ideas for full blog posts about the ideas created by the ideas_task. 

reporting_task:
  description: >
    For each of the 2 ideas, review the context and expand each topic into 2 FULL BLOG POSTs of no less than 800 words. 
    Ensure each blog post is detailed and contains relevant information. If more information is needed, consult your coworker. 
    Format each as a readable and informative blog post of no less than 800 words EACH. Avoid using "in Conclusion" or "Conclusion" or "Call to action" 
    and steer clear of run-on sentences. They should be professional but witty. Avoid large words and run-on sentences. 
    Aim for a cool tone that doesn't sound like an AI.

  expected_output: >
    2 fully-fledged blog posts with main topics and interesting facts of no less than 800 words EACH. Each should be formatted in markdown (without '```'), 
    separated by three spaces, and have a unique title.

# image_task:
#   description: >
#     For each of the 2 ideas, review the context and Generate an image of a beautiful home with a large front yard in {Location} in {year}.

#   expected_output: >
#     2 beautiful images of homes in {Location} in {year}.